# Generated by Django 3.1.7 on 2021-05-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_image', models.ImageField(upload_to='images/')),
                ('item_description', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
