# Generated by Django 3.1.7 on 2021-05-05 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20210505_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to=settings.AUTH_USER_MODEL),
        ),
    ]
