# Generated by Django 3.1.7 on 2021-05-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_category',
            field=models.CharField(choices=[('M', 'Men'), ('F', 'Women'), ('D', 'Decorations'), ('A', 'Accessories')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
